#!/bin/bash
#Copyright 2015 Blackberry Limited
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

#Credits - parts of this code picked up from https://github.com/OpenNebula/addon-iscsi

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh
function GetKey () {
        PY_SCRIPT="import sys;import json;print json.loads(sys.argv[1])[sys.argv[2]];"
        OUTPUT=$(  python -c "$PY_SCRIPT" "$1" "$2"  )
        echo ${OUTPUT}
}

DRIVER_PATH=$(dirname $0)
DRV_ACTION=$1
ID=$2

. "$DRIVER_PATH/saturniscsi.conf"
XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/ID \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/NAME \
                    /DS_DRIVER_ACTION_DATA/IMAGE/ID )
DSID="${XPATH_ELEMENTS[j++]}"
DSNAME="${XPATH_ELEMENTS[j++]}"
IMAGEID="${XPATH_ELEMENTS[j++]}"

RTNSTR=$( . "$DRIVER_PATH/saturniscsi.conf"; curl -s -X GET "${SATURNRINGURL}/api/delete/" \
  -d "iqnini=iqn.iscsihypervisor.$SATURNRINGUSER-$DSNAME-$DSID-$IMAGEID" \
  -u "$SATURNRINGUSER:$SATURNRINGPASSWORD" )

ERROR=$(GetKey "${RTNSTR}" "error")

cat << EOF > /tmp/deletepassedparameters.txt
ERROR: $ERROR
DSID: $DSID
DSName: $DSNAME
SaturnringURL: $SATURNRINGURL
SaturnringUser: $SATURNRINGUSER
SaturnringPassword: Make sure special characters are not causing trouble
ImageID: $IMAGEID
Rtnstr: $RTNSTR
EOF

if [ "$ERROR" != "0" ]
then
read -r -d '' DBGVAR << EOM
Rtnstr: $RTNSTR
Saturn Deletion debugging information
ERROR: $ERROR
DSID: $DSID
DSName: $DSNAME
SaturnringURL: $SATURNRINGURL
SaturnringUser: $SATURNRINGUSER
SaturnringPassword: Make sure special characters are not causing trouble
ImageID: $IMAGEID
EOM
error_message "Saturn datastore image deletion error: $DBGVAR"
exit -1
fi

exit 0
