#!/bin/bash
#Copyright 2015 Blackberry Limited
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.


#Credits - parts of this code picked up from https://github.com/OpenNebula/addon-iscsi

SRC=$1
DST=$2

VMID=$3
DSID=$4

echo $1 $2 $3 $4 > /tmp/enteredln.txt

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

DRIVER_PATH=$(dirname $0)

source ${DRIVER_PATH}/../../datastore/saturniscsi/commonsaturniscsi
#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------
echo $DRIVER_PATH > /tmp/enteredln.txt

IQN=$(SplitA "$SRC" "-_-_-")
PORTAL=$(SplitB "$SRC" "-_-_-")

DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`
DST_DIR=`dirname $DST_PATH`

LINK_CMD=$(cat <<EOF
    set -e
    # discover and login
    mkdir -p $DST_DIR
    $SUDO $(iscsiadm_discovery "$PORTAL")
    $SUDO $(iscsiadm_login "$IQN" "$PORTAL")

    # poll
    while [ ! -L /dev/disk/by-path/*$IQN-lun-0 ]; do
        sleep 1
    done

    # link
    DISK_BY_PATH=\$(ls /dev/disk/by-path/*$IQN-lun-0)
  #  $SUDO $(chmod 777 "\$DISK_BY_PATH")
    ln -s "\$DISK_BY_PATH" "$DST_PATH"
EOF
)
echo $LINK_CMD >> /tmp/enteredln.txt

ssh_exec_and_log "$DST_HOST" "$LINK_CMD" \
        "Error linking $DST_HOST:$IQN"

exit 0
